<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.example.org/schema/1667277780363" xmlns:tns="http://xmlns.example.com/20221101101300" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Emp_Title_SalaryService" targetNamespace="http://xmlns.example.com/20221101101300" xmlns:xsd1="http://www.example.org/emp_title_salary" xmlns:xsd2="http://www.EniqueSolutions/EmployeeDetailPOC/MainSystem">
  <wsdl:import location="../Schemas/Emp_Title_SalarySchema.xsd" namespace="http://www.example.org/schema/1667277780363"/>
  <wsdl:types>
  	<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  		<xsd:import
  			namespace="http://www.example.org/emp_title_salary"
  			schemaLocation="../Schemas/emp_title_salary.xsd">
  		</xsd:import>
  		<xsd:import
  			namespace="http://www.EniqueSolutions/EmployeeDetailPOC/MainSystem"
  			schemaLocation="../Schemas/MainSystem.xsd">
  		</xsd:import></xsd:schema></wsdl:types>
  <wsdl:message name="operationRequest">
    <wsdl:part element="xsd2:emptitlereq" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="operationResponse">
    <wsdl:part element="xsd2:RestResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="operationFault">
    <wsdl:part element="extns:operationFault" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Service">
    <wsdl:operation name="operation">
      <wsdl:input message="tns:operationRequest" name="operationInput"/>
      <wsdl:output message="tns:operationResponse" name="operationOutput"/>
      <wsdl:fault message="tns:operationFault" name="Fault"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
